<?php
	define('_NP_ANALYZE_A', 'Result : ');
	define('_NP_ANALYZE_ACCESSLOG', 'Access Log');
	define('_NP_ANALYZE_ACCESSLOG0', 'Log');
	define('_NP_ANALYZE_ACCESS_PAGE', 'Access Page');
	define('_NP_ANALYZE_ACCESS_HOST', 'Access Host');
	define('_NP_ANALYZE_ADD', 'Add');
	define('_NP_ANALYZE_ADD0', 'Add of this host.<br />');
	define('_NP_ANALYZE_ALL', 'ALL');
	define('_NP_ANALYZE_ALL2', 'Display all monthly result');
	define('_NP_ANALYZE_CANCEL', 'Cancel');
	define('_NP_ANALYZE_CHANGE', 'change');
	define('_NP_ANALYZE_COUNT', ' *Result:');
	define('_NP_ANALYZE_COUNT_CHANGE', 'Total counts change');
	define('_NP_ANALYZE_CSV', 'CSV');
	define('_NP_ANALYZE_CSV0', 'Edit CSV file');
	define('_NP_ANALYZE_CSV1', 'File name');
	define('_NP_ANALYZE_CSV2', 'File size');
	define('_NP_ANALYZE_CSV3', 'Last update time');
	define('_NP_ANALYZE_CSV4', 'Delete of this CSV file?');
	define('_NP_ANALYZE_CSV5', 'Delete of this CSV file.');
	define('_NP_ANALYZE_CSV6', 'Browsing monthly log file');
	define('_NP_ANALYZE_CSV7', 'Not Browsing monthly log file');
	define('_NP_ANALYZE_CSV8', 'Directory name');
	define('_NP_ANALYZE_CSV9', 'Rename');
	define('_NP_ANALYZE_CSV1A', 'old ');
	define('_NP_ANALYZE_CSV1B', 'new ');
	define('_NP_ANALYZE_CSV1C', 'Change a directory name to store CSV file');
	define('_NP_ANALYZE_CSV1D', 'Changing directory name?');
	define('_NP_ANALYZE_DAILY', 'Daily ');
	define('_NP_ANALYZE_DAILY_CHANGE1', ' : Count processing is not completed. Do you do count processing again?');
	define('_NP_ANALYZE_DAILY_CHANGE2', ' Start.');
	define('_NP_ANALYZE_DAILY_CHANGE3', ' Finish.');
	define('_NP_ANALYZE_DATA', 'Analyze');
	define('_NP_ANALYZE_DATE', 'Date');
	define('_NP_ANALYZE_DATE1', 'Date');
	define('_NP_ANALYZE_DAY_AVG', 'Day avg');
	define('_NP_ANALYZE_DAYS', 'Days');
	define('_NP_ANALYZE_DAY0', 'Sun');
	define('_NP_ANALYZE_DAY1', 'Mon');
	define('_NP_ANALYZE_DAY2', 'Tue');
	define('_NP_ANALYZE_DAY3', 'Wed');
	define('_NP_ANALYZE_DAY4', 'Thu');
	define('_NP_ANALYZE_DAY5', 'Fri');
	define('_NP_ANALYZE_DAY6', 'Sat');
	define('_NP_ANALYZE_DB', 'DB');
	define('_NP_ANALYZE_DB0', 'Edit database table');
	define('_NP_ANALYZE_DB1', 'Table');
	define('_NP_ANALYZE_DB2', 'Size');
	define('_NP_ANALYZE_DB3', 'Record');
	define('_NP_ANALYZE_DB4', 'Explanation');
	define('_NP_ANALYZE_DEL', '(<strong>*NOT FOUND!</strong>)');
	define('_NP_ANALYZE_DELETE', 'Access log delete of this host.<br />Count:');
	define('_NP_ANALYZE_DELETE0', 'Delete of this host.<br />');
	define('_NP_ANALYZE_DELETE1', 'Access log delete of XML-RSS.<br />Count:');
	define('_NP_ANALYZE_DELETE2', 'Access log delete of this host?<br />Count:');
	define('_NP_ANALYZE_DELETE3', 'Delete');
	define('_NP_ANALYZE_DELETE4', 'Access log delete of XML-RSS?<br />Count:');
	define('_NP_ANALYZE_DELETE5', 'Delete of old data : ');
	define('_NP_ANALYZE_DELETE6', ' : Do you delete of old data?');
	define('_NP_ANALYZE_DELETE7', ' : Delete of old data.');
	define('_NP_ANALYZE_DELETE8', 'Target tables');
	define('_NP_ANALYZE_DELETE9', ' : Do you set the upper limit? *limit:');
	define('_NP_ANALYZE_DELETEA', ' : Setting the upper limit. *limit:');
	define('_NP_ANALYZE_DELETEB', ' : When you set the upper limit, please set the upper limit at "');
	define('_NP_ANALYZE_DELETEC', '". ');
	define('_NP_ANALYZE_DISTRIBUTION', 'Range of pages');
	define('_NP_ANALYZE_EDIT', 'Edit');
	define('_NP_ANALYZE_EDIT0', 'Edit of this host.<br />');
	define('_NP_ANALYZE_EMP', 'Do you empty this table?');
	define('_NP_ANALYZE_EMP0', 'Empty table');
	define('_NP_ANALYZE_EMP1', 'emptied.');
	define('_NP_ANALYZE_ERROR_PAGE', 'Error Page');
	define('_NP_ANALYZE_EXTRACT', 'Extract');
	define('_NP_ANALYZE_EXPORT', 'Export');
	define('_NP_ANALYZE_EXPORT0', 'Store this table');
	define('_NP_ANALYZE_EXPORT1', 'Store a CSV file');
	define('_NP_ANALYZE_GROUP', 'Group');
	define('_NP_ANALYZE_GROUP0', 'Read more');
	define('_NP_ANALYZE_GROUP1', ' count result');
	define('_NP_ANALYZE_HIT', 'PV');
	define('_NP_ANALYZE_HIT1', 'PV1');
	define('_NP_ANALYZE_INIT', ' Initialization');
	define('_NP_ANALYZE_INIT0', ' Initialization?');
	define('_NP_ANALYZE_LAST', 'Monthly Access Analysis');
	define('_NP_ANALYZE_LAST1', 'Last ');
	define('_NP_ANALYZE_LAST2', 'days Access Analysis');
	define('_NP_ANALYZE_MONTH', 'Month');
	define('_NP_ANALYZE_MONTHLY', 'Monthly ');
	define('_NP_ANALYZE_NEXT_PAGE', 'Next Page');
	define('_NP_ANALYZE_NG', 'Exclusion HOST');
	define('_NP_ANALYZE_NG0', 'NG');
	define('_NP_ANALYZE_NG1A', 'Exclusion Count');
	define('_NP_ANALYZE_NG1B', 'Exclusion Count &amp; Log');
	define('_NP_ANALYZE_NG1', 'Exclusion');
	define('_NP_ANALYZE_NG2', 'Name');
	define('_NP_ANALYZE_NG3', 'Host name');
	define('_NP_ANALYZE_NG4', 'Initialization');
	define('_NP_ANALYZE_OPTIONS', 'Options for NP_Analyze');
	define('_NP_ANALYZE_OPTIONS0', 'Options');
	define('_NP_ANALYZE_OP_1', '1. Do you count at loggedin?');
	define('_NP_ANALYZE_OP_2', '2. Do you delete tables on uninstall?');
	define('_NP_ANALYZE_OP_3', '3. Do you send E-mail daily report?');
	define('_NP_ANALYZE_OP_4', '4. Count start date. (*ex. ');
	define('_NP_ANALYZE_OP_5', '5. Showing limit at Admin area. (* 1~30 )');
	define('_NP_ANALYZE_OP_6', '6. Range of hit page level. (*ex. 1/5/9/49)');
	define('_NP_ANALYZE_OP_7', '7. Do you show NP_Analyze copyright?');
	define('_NP_ANALYZE_OP_8', '8. QuickMenu?');
	define('_NP_ANALYZE_OP_9', '9. Permission of browsing analysis. MemberID. (*ex. 2/3/8 )');
	define('_NP_ANALYZE_OP_10', '10. Do you browse monthly log file?');
	define('_NP_ANALYZE_OP_11', '11. Do you count at RSS-XML?');
	define('_NP_ANALYZE_OP_12', '12. A directory name to store CSV file. (*ex. analyze)');
	define('_NP_ANALYZE_OP_13', '13. Do you display daily time distinction?');
	define('_NP_ANALYZE_OP_14', '14. The number of the letters of page title. (*ex. 18)');
	define('_NP_ANALYZE_OP_15', '15. Do you display end URL of a Blog page?');
	define('_NP_ANALYZE_OP_16', '16. Setting the upper limit at each monthly results.');
	define('_NP_ANALYZE_OP_17', '17. Line graph of Daily time distinction. (*ex. 1.5)');
	define('_NP_ANALYZE_OP_18', '18. The number to handle in processing at a time. (*ex. 5000)');
	define('_NP_ANALYZE_OP_19', '19. Time Offset. (*ex. 5)');
	define('_NP_ANALYZE_OP_20', '20. Do you send E-mail monthly report?');
	define('_NP_ANALYZE_OP_21', '21. Default Domain Search. (*ex: ');
	define('_NP_ANALYZE_OP_210', '.com/.net/.org');
	define('_NP_ANALYZE_OP_22', '22. Counter option. <%Analyze(count,all)%> (*ex: ');
	define('_NP_ANALYZE_OP_220', 'Total:/ Today:/ Yesterday:');
	define('_NP_ANALYZE_PAGE', 'Each Page');
	define('_NP_ANALYZE_PENEXT', 'Next Page');
	define('_NP_ANALYZE_PEPREV', 'Prev Page');
	define('_NP_ANALYZE_REFRESH', 'Refresh');
	define('_NP_ANALYZE_REFERER_PAGE', 'Referer Page');
	define('_NP_ANALYZE_ROBOT', 'Robots');
	define('_NP_ANALYZE_SEARCH', 'Search');
	define('_NP_ANALYZE_SEARCH_ENGINE', 'Search Engine');
	define('_NP_ANALYZE_SEARCH_PAGE', 'Search Page');
	define('_NP_ANALYZE_SEARCH_WORD', 'Search Word');
	define('_NP_ANALYZE_SORT', 'Sort');
	define('_NP_ANALYZE_SQLQUERY', 'SQL-query');
	define('_NP_ANALYZE_TABLE', 'Edit this table');
	define('_NP_ANALYZE_T0', 'Search Engine');
	define('_NP_ANALYZE_T1', 'Total Visit &amp; Page-View');
	define('_NP_ANALYZE_T2', 'Host');
	define('_NP_ANALYZE_T3', 'Day Access Log');
	define('_NP_ANALYZE_T4', 'Exclusion Host');
	define('_NP_ANALYZE_T5', 'Popular Page');
	define('_NP_ANALYZE_T6', 'Page Pattern');
	define('_NP_ANALYZE_T7', 'Page Search Word');
	define('_NP_ANALYZE_T8', 'Search Word');
	define('_NP_ANALYZE_T9', 'Referer');
	define('_NP_ANALYZE_TA', 'Robot');
	define('_NP_ANALYZE_TB', 'Monthly Access Log');
	define('_NP_ANALYZE_TIME', 'Time');
	define('_NP_ANALYZE_TIME1', 'Daily time distinction');
	define('_NP_ANALYZE_TIME2', 'This hour Access Log');
	define('_NP_ANALYZE_TIME3', '(*Daily time distinction)');
	define('_NP_ANALYZE_TITLE', 'Access Analysis');
	define('_NP_ANALYZE_TOTAL', 'Total');
	define('_NP_ANALYZE_TOTAL0', 'Total');
	define('_NP_ANALYZE_TOTAL1', 'Total Access Analysis');
	define('_NP_ANALYZE_TRUNCATE', 'Truncate Temporary Table');
	define('_NP_ANALYZE_UPDATE', 'Please update this plugin. ');
	define('_NP_ANALYZE_UPGRADE', 'Version Check');
	define('_NP_ANALYZE_VISIT', 'Hit');
	define('_NP_ANALYZE_YES', 'Yes');
