<?php
	define('_NP_ANALYZE_A', '実行結果：');
	define('_NP_ANALYZE_ACCESSLOG', 'アクセスログ');
	define('_NP_ANALYZE_ACCESSLOG0', 'ログ');
	define('_NP_ANALYZE_ACCESS_PAGE', 'アクセスページ');
	define('_NP_ANALYZE_ACCESS_HOST', 'アクセスホスト');
	define('_NP_ANALYZE_ADD', '追加');
	define('_NP_ANALYZE_ADD0', 'このホストを追加しました<br />');
	define('_NP_ANALYZE_ALL', '全表示');
	define('_NP_ANALYZE_ALL2', '月別の集計結果を一括して表示');
	define('_NP_ANALYZE_CANCEL', 'キャンセル');
	define('_NP_ANALYZE_CHANGE', '変更');
	define('_NP_ANALYZE_COUNT', '　*表示件数：');
	define('_NP_ANALYZE_COUNT_CHANGE', '累計カウント数の変更');
	define('_NP_ANALYZE_CSV', 'CSV');
	define('_NP_ANALYZE_CSV0', 'CSVファイルの状況');
	define('_NP_ANALYZE_CSV1', 'ファイル名');
	define('_NP_ANALYZE_CSV2', 'サイズ');
	define('_NP_ANALYZE_CSV3', '最終更新時間');
	define('_NP_ANALYZE_CSV4', 'CSVファイルを削除しますか？');
	define('_NP_ANALYZE_CSV5', 'CSVファイルを削除しました');
	define('_NP_ANALYZE_CSV6', '月別のアクセスログを使用する');
	define('_NP_ANALYZE_CSV7', '月別のアクセスログを使用しない');
	define('_NP_ANALYZE_CSV8', 'ディレクトリ名');
	define('_NP_ANALYZE_CSV9', '名称変更');
	define('_NP_ANALYZE_CSV1A', '現在の');
	define('_NP_ANALYZE_CSV1B', '新しい');
	define('_NP_ANALYZE_CSV1C', 'CSVファイルを保存するディレクトリ名称を変更する必要があります');
	define('_NP_ANALYZE_CSV1D', 'ディレクトリ名称を変更してもいいですか？');
	define('_NP_ANALYZE_DAILY', '日別の');
	define('_NP_ANALYZE_DAILY_CHANGE1', 'の集計処理が完了していません。集計処理を再び行ないますか？');
	define('_NP_ANALYZE_DAILY_CHANGE2', ' 集計処理の開始時間');
	define('_NP_ANALYZE_DAILY_CHANGE3', ' 集計処理の完了時間');
	define('_NP_ANALYZE_DATA', 'アクセス解析');
	define('_NP_ANALYZE_DATE', '日付');
	define('_NP_ANALYZE_DATE1', '日');
	define('_NP_ANALYZE_DAY_AVG', '日平均');
	define('_NP_ANALYZE_DAYS', '日間');
	define('_NP_ANALYZE_DAY0', '日');
	define('_NP_ANALYZE_DAY1', '月');
	define('_NP_ANALYZE_DAY2', '火');
	define('_NP_ANALYZE_DAY3', '水');
	define('_NP_ANALYZE_DAY4', '木');
	define('_NP_ANALYZE_DAY5', '金');
	define('_NP_ANALYZE_DAY6', '土');
	define('_NP_ANALYZE_DB', 'DB');
	define('_NP_ANALYZE_DB0', 'データベースの状況');
	define('_NP_ANALYZE_DB1', 'テーブル名');
	define('_NP_ANALYZE_DB2', 'サイズ');
	define('_NP_ANALYZE_DB3', 'レコード数');
	define('_NP_ANALYZE_DB4', '説明');
	define('_NP_ANALYZE_DEL', '(<strong>*NOT FOUND!</strong>)');
	define('_NP_ANALYZE_DELETE', 'このホストのアクセスログを削除しました<br />削除数：');
	define('_NP_ANALYZE_DELETE0', 'このホストを削除しました<br />');
	define('_NP_ANALYZE_DELETE1', 'XML-RSSのアクセスログを削除しました<br />削除数：');
	define('_NP_ANALYZE_DELETE2', 'このホストのアクセスログを削除してもいいですか？<br />削除数：');
	define('_NP_ANALYZE_DELETE3', '削除');
	define('_NP_ANALYZE_DELETE4', 'XML-RSSのアクセスログを削除してもいいですか？<br />削除数：');
	define('_NP_ANALYZE_DELETE5', '集計データの削除：');
	define('_NP_ANALYZE_DELETE6', '以前の集計データを削除しますか？');
	define('_NP_ANALYZE_DELETE7', '以前の集計データを削除しました');
	define('_NP_ANALYZE_DELETE8', '対象テーブル');
	define('_NP_ANALYZE_DELETE9', 'の集計データに上限を設定しますか？　上限数：');
	define('_NP_ANALYZE_DELETEA', 'の集計データに上限を設定しました。　上限数：');
	define('_NP_ANALYZE_DELETEB', 'の集計データの上限数を指定する場合、「');
	define('_NP_ANALYZE_DELETEC', '」において上限を設定してください。');
	define('_NP_ANALYZE_DISTRIBUTION', 'ページ数の分布');
	define('_NP_ANALYZE_EDIT', '編集');
	define('_NP_ANALYZE_EDIT0', 'このホストの設定を変更しました<br />');
	define('_NP_ANALYZE_EMP', 'テーブルを空にしますか？');
	define('_NP_ANALYZE_EMP0', 'テーブルを空にする');
	define('_NP_ANALYZE_EMP1', 'テーブルを空にしました');
	define('_NP_ANALYZE_ERROR_PAGE', 'エラーページ');
	define('_NP_ANALYZE_EXTRACT', '絞込');
	define('_NP_ANALYZE_EXPORT', 'エクスポート');
	define('_NP_ANALYZE_EXPORT0', 'このテーブルを保存する');
	define('_NP_ANALYZE_EXPORT1', 'ＣＳＶファイルを保存する');
	define('_NP_ANALYZE_GROUP', '集計');
	define('_NP_ANALYZE_GROUP0', '集計結果をもっと見る');
	define('_NP_ANALYZE_GROUP1', '集計結果');
	define('_NP_ANALYZE_HIT', 'PV');
	define('_NP_ANALYZE_HIT1', '直帰数');
	define('_NP_ANALYZE_INIT', 'を初期化しました');
	define('_NP_ANALYZE_INIT0', 'を初期化しますか？');
	define('_NP_ANALYZE_LAST', '月別のアクセス状況');
	define('_NP_ANALYZE_LAST1', '過去');
	define('_NP_ANALYZE_LAST2', '日間のアクセス状況');
	define('_NP_ANALYZE_MONTH', '月別');
	define('_NP_ANALYZE_MONTHLY', '月別の');
	define('_NP_ANALYZE_NEXT_PAGE', '次のページ');
	define('_NP_ANALYZE_NG', '除外ホスト設定');
	define('_NP_ANALYZE_NG0', 'NG');
	define('_NP_ANALYZE_NG1A', 'カウント除外');
	define('_NP_ANALYZE_NG1B', 'カウント＆ログ除外');
	define('_NP_ANALYZE_NG1', '除外設定');
	define('_NP_ANALYZE_NG2', '名称');
	define('_NP_ANALYZE_NG3', 'ホスト名');
	define('_NP_ANALYZE_NG4', '初期設定に戻す');
	define('_NP_ANALYZE_OPTIONS', 'オプション設定');
	define('_NP_ANALYZE_OPTIONS0', '設定');
	define('_NP_ANALYZE_OP_1', '1. ログイン時にカウントしますか？');
	define('_NP_ANALYZE_OP_2', '2. アンインストール時にテーブルを削除しますか？');
	define('_NP_ANALYZE_OP_3', '3. 毎日メールでアクセス解析レポートを送りますか？');
	define('_NP_ANALYZE_OP_4', '4. アクセス解析の開始日 (例. ');
	define('_NP_ANALYZE_OP_5', '5. アクセス解析画面での各解析結果の表示件数（例. 1～30）');
	define('_NP_ANALYZE_OP_6', '6. 各訪問者の閲覧ページ数の分布（例. 1/5/9/49）');
	define('_NP_ANALYZE_OP_7', '7. NP_Analyzeへのリンクを表示しますか？');
	define('_NP_ANALYZE_OP_8', '8. 「QuickMenu」に追加しますか？');
	define('_NP_ANALYZE_OP_9', '9. アクセス解析画面の閲覧を許可するメンバーID（例. 2/3/8）');
	define('_NP_ANALYZE_OP_10', '10. 月別ログファイルを閲覧しますか？');
	define('_NP_ANALYZE_OP_11', '11. ＲＳＳへのアクセスをカウントしますか？');
	define('_NP_ANALYZE_OP_12', '12. CSVファイルを保存するディレクトリ名（例. analyze）');
	define('_NP_ANALYZE_OP_13', '13. 本日の時間別アクセス状況を表示しますか？');
	define('_NP_ANALYZE_OP_14', '14. ページタイトルの表示文字数（例. 18）');
	define('_NP_ANALYZE_OP_15', '15. Blogページの末尾URLを表示しますか？');
	define('_NP_ANALYZE_OP_16', '16. 各月別集計の上限データ数（※空白の場合は上限なし）');
	define('_NP_ANALYZE_OP_17', '17. 時間別アクセス状況の棒線グラフの表示倍率（例. 1.5）');
	define('_NP_ANALYZE_OP_18', '18. 集計処理等において一度に処理する件数（例.5000）');
	define('_NP_ANALYZE_OP_19', '19. サーバ時刻との時差（例.5）');
	define('_NP_ANALYZE_OP_20', '20. 月一度メールでアクセス解析レポートを送りますか？');
	define('_NP_ANALYZE_OP_21', '21. 検索対象ドメインの指定 (例: ');
	define('_NP_ANALYZE_OP_210', '.com/.jp/.co.jp/.go.jp/.ac.jp');
	define('_NP_ANALYZE_OP_22', '22. カウンター表示オプション <%Analyze(count,all)%> (例. ');
	define('_NP_ANALYZE_OP_220', '総アクセス数:/　今日:/　昨日:');
	define('_NP_ANALYZE_PAGE', 'ページ別の');
	define('_NP_ANALYZE_PENEXT', '次のページ');
	define('_NP_ANALYZE_PEPREV', '前のページ');
	define('_NP_ANALYZE_REFERER_PAGE', 'リファー元');
	define('_NP_ANALYZE_REFRESH', '再読込');
	define('_NP_ANALYZE_ROBOT', 'ロボット等');
	define('_NP_ANALYZE_SEARCH', '検索');
	define('_NP_ANALYZE_SEARCH_ENGINE', '検索エンジン');
	define('_NP_ANALYZE_SEARCH_PAGE', '検索ページ');
	define('_NP_ANALYZE_SEARCH_WORD', '検索ワード');
	define('_NP_ANALYZE_SORT', 'ソート');
	define('_NP_ANALYZE_SQLQUERY', '実行されたSQLクエリー');
	define('_NP_ANALYZE_TABLE', 'このテーブルを編集する');
	define('_NP_ANALYZE_T0', '検索エンジン');
	define('_NP_ANALYZE_T1', '訪問者数とページビュー');
	define('_NP_ANALYZE_T2', 'ホスト');
	define('_NP_ANALYZE_T3', '本日のアクセスログ');
	define('_NP_ANALYZE_T4', '除外ホスト');
	define('_NP_ANALYZE_T5', '人気ページ');
	define('_NP_ANALYZE_T6', '移動パターン');
	define('_NP_ANALYZE_T7', 'ページ別の検索語');
	define('_NP_ANALYZE_T8', '検索語');
	define('_NP_ANALYZE_T9', 'リファー元');
	define('_NP_ANALYZE_TA', 'ロボット等');
	define('_NP_ANALYZE_TB', '月別のアクセスログ');
	define('_NP_ANALYZE_TIME', '時間');
	define('_NP_ANALYZE_TIME1', '本日の時間別アクセス状況');
	define('_NP_ANALYZE_TIME2', 'この時間帯のアクセスログ');
	define('_NP_ANALYZE_TIME3', '(*時間別アクセス状況)');
	define('_NP_ANALYZE_TITLE', 'アクセス解析');
	define('_NP_ANALYZE_TOTAL', '累計');
	define('_NP_ANALYZE_TOTAL0', '計');
	define('_NP_ANALYZE_TOTAL1', '累計のアクセス状況');
	define('_NP_ANALYZE_TRUNCATE', '一時テーブルを空にする');
	define('_NP_ANALYZE_UPDATE', 'プラグインを一度アンインストールした後、再度インストールし直してください。');
	define('_NP_ANALYZE_UPGRADE', '最新バージョンのチェック');
	define('_NP_ANALYZE_VISIT', 'Hit');
	define('_NP_ANALYZE_YES', 'はい');
?>